apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- amq-operator-subscription.yaml
- amq-broker.yaml
- messaging-deployment.yaml
- messaging-svc.yaml

configMapGenerator:
- name: messaging-configmap
  envs:
  - messaging-configmap.properties